# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Время')),
                ('event', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Начало голосования')),
            ],
        ),
        migrations.CreateModel(
            name='TimePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(verbose_name='Длительность первой фазы')),
                ('second', models.IntegerField(verbose_name='Длительность второй фазы')),
                ('active', models.BooleanField(default=True, verbose_name='Голосование активно')),
                ('votes', models.IntegerField(default=0, verbose_name='Всего проголосовало')),
                ('start', models.DateTimeField(auto_now=True, verbose_name='Начало голосования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='firstphase',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TimePhase', verbose_name='Номер голосования'),
        ),
        migrations.AddField(
            model_name='firstphase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
